# Efficient linear algebra in python

Here, we will see some **do** and **don't** int order to obtain an efficient python code when dealing with arrays.

## Built-in lists

Python has a built-in `list`, as well as a `tuple`:

In [2]:
A = [1, 2, 4]
B = (4, 5 ,6)
print(type(A), type(B))

<class 'list'> <class 'tuple'>


The `list` is created using the square brackets, while the `tuple` uses the usual round brackets.
At our level, there is no differences between the two, but using the `list` is more usual.

To create a `list`, we usualy uses the "constuctor syntax".
For instance, let's create a `list` with 1000 elements squared.

In [3]:
N = 1000
A = [ float(i)**2 for i in range(N)]
print(A[:10])

[0.0, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0]


There are some builtin function for the list, as the `sum`. Those functions are usualy faster than self-made function.

For Example, let's calculate the sum of the list:

In [4]:
%%timeit
tmp = 0
for a in A:
    tmp += a

35.4 µs ± 1.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [5]:
%%timeit
sum(A)

5.36 µs ± 177 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


We can see that the built-in`sum` fonction of the `list` can be significantly faster than a `for` loop.

**On the efficiency of the list**:

Unfortunatly, `lists` are not very efficent, as the structure is made to `append` or `pop` elements easily. Hence, the list store the reference of the data elsewhere in the memory.


## `numpy`

`numpy` is a package that is made to store `arrays` (vectore, matrix, etc.) more efficiently.
We usualy import it as `np`.

Transforming a `list` to an `array` is easy. Once the data is stored as an array, the function will be more efficient !

In [6]:
import numpy as np

Anp = np.array(A)

In [7]:
%%timeit
Anp.sum()

2.73 µs ± 117 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Using `numpy` reduced the computational time of `sum` compare the the `list` `sum`, with is more that `10x` faster thant the `for` loop !

## Multi-dimentional array
aka: `ndarray`.

`numpy` is design to deals with nd arrays.


In [8]:
print("Identity matix : ")
I = 2*np.eye(5)
print(I)


A = np.ones(shape=(4,5))

print("Scalair product :")
A.dot(I)

Identity matix : 
[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]
Scalair product :


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

## Vectorizing

For $99\%$ of the time, a `for` loop will be slower that a build-in function of `numpy`.

Transforming a loop into a matrix product, by example, is name **vectorizing** an operation.
You should always try to vectorise everything.


In [13]:
# Here is two vectors of size 100
A = np.linspace(0, 5, 100)
print(A[:5])
B = np.linspace(30, 5, 100)

[0.         0.05050505 0.1010101  0.15151515 0.2020202 ]


In [16]:
print("Scalar product between Two vectors: ")
%timeit C = A.dot(B)

Scalar product between Two vectors: 
722 ns ± 22.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [17]:
%%timeit
C = 0
for a, b in zip(A, B):
    C += a*b

48.3 µs ± 1.08 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


The `numpy` scalar product is more than 50 times faster ! (it may depend on the computer you uses)

### Remarque
`numpy` usually `map` the operations.
That is, the product operator `*` or the function `np.exp` will actually be applied element-wise.

In [18]:
(A*B)[:5]

array([0.        , 1.50239771, 2.97928783, 4.43067034, 5.85654525])

In [19]:
np.exp(A)[:5]

array([1.        , 1.05180218, 1.10628782, 1.16359593, 1.22387273])

# Conclusion

This introductions to arrays was quite lite, but you should have gain some information.

For a deeper introductions to arrays, you can see [this notebook](https://github.com/pierreablin/python-sessions/blob/master/Reference_arrays_args.ipynb)

For a deeper discussion on fast python calculations, you can see [this notebook](https://github.com/pierreablin/python-sessions/blob/master/fast_python.ipynb)